### ISSUE TITLE
Unquote throws java.lang.String cannot be cast to clojure.lang.IFn

### ISSUE THREAD

**Issue by arichiardi** [ninjudd/classlojure#8]
Hello folks!

I decided to use this project in a Maven Plugin following `pallet/zi`, but running something as simple as:

`(clojure.pprint/pprint ~classpath-urls)`

In a `1.9.0-alpha14` throws:

```
[ERROR] InvocationTargetException: java.lang.String cannot be cast to clojure.lang.IFn
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at classlojure.core$invoke_in_STAR_.invokeStatic(core.clj:53)
	at classlojure.core$invoke_in_STAR_.doInvoke(core.clj:49)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at classlojure.core$eval_in$print_read_eval__541.invoke(core.clj:75)
	at classlojure.core$eval_in.invokeStatic(core.clj:77)
	at classlojure.core$eval_in.doInvoke(core.clj:67)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at rest_resources_viz.extract$run_extractor.invokeStatic(extract.clj:47)
	at rest_resources_viz.extract$run_extractor.invoke(extract.clj:29)
	at rest_resources_viz.extract.ExtractMojo.execute(extract.clj:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn
	at clojure.core$eval5325.invokeStatic(NO_SOURCE_FILE:0)
	at clojure.core$eval5325.invoke(NO_SOURCE_FILE)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.lang.Compiler.eval(Compiler.java:6941)
	... 36 more
[ERROR] 
```

If I wrap that in a list, anything that simulates a function call, it seems to be working:

`(clojure.pprint/pprint ~(vec classpath-urls))`

Is this expected behavior?

**Comment by arichiardi** [comment]
I can answer to my own question in a way. It is kind of expected and I realized this after having had a look at the code and thought about it a bit more.
Given that the last parameter to `eval-in` will be evaluated, kind of like the return of a macro, every list that is passed in with no quote needs a function in first position. If it's data in a list and we want to evaluate that, then we need to employ the `'~` pattern.

Let me close this one and update the README.
